#include "pet_sprites.h"
#include "pet_state.h"

#define MK(name) SpriteData{ SPRITE_##name, SPRITE_##name##_FRAMES }

// =============================================================================
// Conjuntos de sprites por fase/caminho
// =============================================================================

// Fase 1 (bebê) - tudo sem sufixo
static const PhaseSpriteSet SET_FASE1 = {
    MK(IDLE), MK(SLEEPING), MK(SICK), MK(DIRTY), MK(COLD), MK(HOT),
    MK(BATH), MK(DRINKING), MK(CARESSING), MK(READING), MK(APPLYINGINJECTION),
    MK(SWALLOWING), MK(CELEBRATING), MK(LOSING)
};

// Fase 2 (filhote) - sufixo "2"
static const PhaseSpriteSet SET_FASE2 = {
    MK(IDLE2), MK(SLEEPING2), MK(SICK2), MK(DIRTY2), MK(COLD2), MK(HOT2),
    MK(BATH2), MK(DRINKING2), MK(CARESSING2), MK(READING2), MK(APPLYINGINJECTION2),
    MK(SWALLOWING2), MK(CELEBRATING2), MK(LOSING2)
};

// Fase 3 - 3 caminhos
static const PhaseSpriteSet SET_FASE3_TREX = {
    MK(IDLE3TYRANNOSAURUS), MK(SLEEPING3TYRANNOSAURUS), MK(SICK3TYRANNOSAURUS),
    MK(DIRTY3TYRANNOSAURUS), MK(COLD3TYRANNOSAURUS), MK(HOT3TYRANNOSAURUS),
    MK(BATH3TYRANNOSAURUS), MK(DRINKING3TYRANNOSAURUS), MK(CARESSING3TYRANNOSAURUS),
    MK(READING2), MK(APPLYINGINJECTION3TYRANNOSAURUS),  // reading só existe até fase 2
    MK(SWALLOWING3TYRANNOSAURUS), MK(CELEBRATING3TYRANNOSAURUS), MK(LOSING3TYRANNOSAURUS)
};
static const PhaseSpriteSet SET_FASE3_TRICER = {
    MK(IDLE3TRICERATOPS), MK(SLEEPING3TRICERATOPS), MK(SICK3TRICERATOPS),
    MK(DIRTY3TRICERATOPS), MK(COLD3TRICERATOPS), MK(HOT3TRICERATOPS),
    MK(BATH3TRICERATOPS), MK(DRINKING3TRICERATOPS), MK(CARESSING3TRICERATOPS),
    MK(READING2), MK(APPLYINGINJECTION3TRICERATOPS),
    MK(SWALLOWING3TRICERATOPS), MK(CELEBRATING3TRICERATOPS), MK(LOSING3TRICERATOPS)
};
static const PhaseSpriteSet SET_FASE3_BRONTO = {
    MK(IDLE3BRONTOSAURUS), MK(SLEEPING3BRONTOSAURUS), MK(SICK3BRONTOSAURUS),
    MK(DIRTY3BRONTOSAURUS), MK(COLD3BRONTOSAURUS), MK(HOT3BRONTOSAURUS),
    MK(BATH3BRONTOSAURUS), MK(DRINKING3BRONTOSAURUS), MK(CARESSING3BRONTOSAURUS),
    MK(READING2), MK(APPLYINGINJECTION3BRONTOSAURUS),
    MK(SWALLOWING3BRONTOSAURUS), MK(CELEBRATING3BRONTOSAURUS), MK(LOSING3BRONTOSAURUS)
};

// Fase 5 - 3 caminhos
static const PhaseSpriteSet SET_FASE5_TREX = {
    MK(IDLE5TYRANNOSAURUS), MK(SLEEPING5TYRANNOSAURUS), MK(SICK5TYRANNOSAURUS),
    MK(DIRTY5TYRANNOSAURUS), MK(COLD5TYRANNOSAURUS), MK(HOT5TYRANNOSAURUS),
    MK(BATH5TYRANNOSAURUS), MK(DRINKING5TYRANNOSAURUS), MK(CARESSING5TYRANNOSAURUS),
    MK(READING2), MK(APPLYINGINJECTION5TYRANNOSAURUS),
    MK(SWALLOWING5TYRANNOSAURUS), MK(CELEBRATING5TYRANNOSAURUS), MK(LOSING5TYRANNOSAURUS)
};
static const PhaseSpriteSet SET_FASE5_TRICER = {
    MK(IDLE5TRICERATOPS), MK(SLEEPING5TRICERATOPS), MK(SICK5TRICERATOPS),
    MK(DIRTY5TRICERATOPS), MK(COLD5TRICERATOPS), MK(HOT5TRICERATOPS),
    MK(BATH5TRICERATOPS), MK(DRINKING5TRICERATOPS), MK(CARESSING5TRICERATOPS),
    MK(READING2), MK(APPLYINGINJECTION5TRICERATOPS),
    MK(SWALLOWING5TRICERATOPS), MK(CELEBRATING5TRICERATOPS), MK(LOSING5TRICERATOPS)
};
static const PhaseSpriteSet SET_FASE5_BRONTO = {
    MK(IDLE5BRONTOSAURUS), MK(SLEEPING5BRONTOSAURUS), MK(SICK5BRONTOSAURUS),
    MK(DIRTY5BRONTOSAURUS), MK(COLD5BRONTOSAURUS), MK(HOT5BRONTOSAURUS),
    MK(BATH5BRONTOSAURUS), MK(DRINKING5BRONTOSAURUS), MK(CARESSING5BRONTOSAURUS),
    MK(READING2), MK(APPLYINGINJECTION5BRONTOSAURUS),
    MK(SWALLOWING5BRONTOSAURUS), MK(CELEBRATING5BRONTOSAURUS), MK(LOSING5BRONTOSAURUS)
};

// Fase 7 - 3 caminhos
static const PhaseSpriteSet SET_FASE7_TREX = {
    MK(IDLE7TYRANNOSAURUS), MK(SLEEPING7TYRANNOSAURUS), MK(SICK7TYRANNOSAURUS),
    MK(DIRTY7TYRANNOSAURUS), MK(COLD7TYRANNOSAURUS), MK(HOT7TYRANNOSAURUS),
    MK(BATH7TYRANNOSAURUS), MK(DRINKING7TYRANNOSAURUS), MK(CARESSING7TYRANNOSAURUS),
    MK(READING2), MK(APPLYINGINJECTION7TYRANNOSAURUS),
    MK(SWALLOWING7TYRANNOSAURUS), MK(CELEBRATING7TYRANNOSAURUS), MK(LOSING7TYRANNOSAURUS)
};
static const PhaseSpriteSet SET_FASE7_TRICER = {
    MK(IDLE7TRICERATOPS), MK(SLEEPING7TRICERATOPS), MK(SICK7TRICERATOPS),
    MK(DIRTY7TRICERATOPS), MK(COLD7TRICERATOPS), MK(HOT7TRICERATOPS),
    MK(BATH7TRICERATOPS), MK(DRINKING7TRICERATOPS), MK(CARESSING7TRICERATOPS),
    MK(READING2), MK(APPLYINGINJECTION7TRICERATOPS),
    MK(SWALLOWING7TRICERATOPS), MK(CELEBRATING7TRICERATOPS), MK(LOSING7TRICERATOPS)
};
static const PhaseSpriteSet SET_FASE7_BRONTO = {
    MK(IDLE7BRONTOSAURUS), MK(SLEEPING7BRONTOSAURUS), MK(SICK7BRONTOSAURUS),
    MK(DIRTY7BRONTOSAURUS), MK(COLD7BRONTOSAURUS), MK(HOT7BRONTOSAURUS),
    MK(BATH7BRONTOSAURUS), MK(DRINKING7BRONTOSAURUS), MK(CARESSING7BRONTOSAURUS),
    MK(READING2), MK(APPLYINGINJECTION7BRONTOSAURUS),
    MK(SWALLOWING7BRONTOSAURUS), MK(CELEBRATING7BRONTOSAURUS), MK(LOSING7BRONTOSAURUS)
};

// Fase 9 - 3 caminhos. Não tem bath/drinking/applyingInjection — fallback fase 7.
static const PhaseSpriteSet SET_FASE9_TREX = {
    MK(IDLE9TYRANNOSAURUS), MK(SLEEPING9TYRANNOSAURUS), MK(SICK9TYRANNOSAURUS),
    MK(DIRTY9TYRANNOSAURUS), MK(COLD9TYRANNOSAURUS), MK(HOT9TYRANNOSAURUS),
    MK(BATH7TYRANNOSAURUS), MK(DRINKING7TYRANNOSAURUS), MK(CARESSING9TYRANNOSAURUS),
    MK(READING2), MK(APPLYINGINJECTION7TYRANNOSAURUS),
    MK(SWALLOWING9TYRANNOSAURUS), MK(CELEBRATING9TYRANNOSAURUS), MK(LOSING9TYRANNOSAURUS)
};
static const PhaseSpriteSet SET_FASE9_TRICER = {
    MK(IDLE9TRICERATOPS), MK(SLEEPING9TRICERATOPS), MK(SICK9TRICERATOPS),
    MK(DIRTY9TRICERATOPS), MK(COLD9TRICERATOPS), MK(HOT9TRICERATOPS),
    MK(BATH7TRICERATOPS), MK(DRINKING7TRICERATOPS), MK(CARESSING9TRICERATOPS),
    MK(READING2), MK(APPLYINGINJECTION7TRICERATOPS),
    MK(SWALLOWING9TRICERATOPS), MK(CELEBRATING9TRICERATOPS), MK(LOSING9TRICERATOPS)
};
static const PhaseSpriteSet SET_FASE9_BRONTO = {
    MK(IDLE9BRONTOSAURUS), MK(SLEEPING9BRONTOSAURUS), MK(SICK9BRONTOSAURUS),
    MK(DIRTY9BRONTOSAURUS), MK(COLD9BRONTOSAURUS), MK(HOT9BRONTOSAURUS),
    MK(BATH7BRONTOSAURUS), MK(DRINKING7BRONTOSAURUS), MK(CARESSING9BRONTOSAURUS),
    MK(READING2), MK(APPLYINGINJECTION7BRONTOSAURUS),
    MK(SWALLOWING9BRONTOSAURUS), MK(CELEBRATING9BRONTOSAURUS), MK(LOSING9BRONTOSAURUS)
};

const PhaseSpriteSet* getCurrentPhaseSet() {
    uint8_t f = pet.faseEvolucao;
    uint8_t c = pet.caminho;
    if (f <= 1) return &SET_FASE1;
    if (f == 2) return &SET_FASE2;
    if (f == 3) {
        if (c == 1) return &SET_FASE3_TREX;
        if (c == 2) return &SET_FASE3_TRICER;
        return &SET_FASE3_BRONTO;
    }
    if (f == 5) {
        if (c == 1) return &SET_FASE5_TREX;
        if (c == 2) return &SET_FASE5_TRICER;
        return &SET_FASE5_BRONTO;
    }
    if (f == 7) {
        if (c == 1) return &SET_FASE7_TREX;
        if (c == 2) return &SET_FASE7_TRICER;
        return &SET_FASE7_BRONTO;
    }
    if (f == 9) {
        if (c == 1) return &SET_FASE9_TREX;
        if (c == 2) return &SET_FASE9_TRICER;
        return &SET_FASE9_BRONTO;
    }
    return &SET_FASE1;
}

// Sprites do jokenpô — só fase 1 no original
SpriteData spritePetPlayPaper()    { return MK(PETSELECTINGPLAYPAPER); }
SpriteData spritePetPlayRock()     { return MK(PETSELECTINGPLAYROCK); }
SpriteData spritePetPlayScissors() { return MK(PETSELECTINGPLAYSCISSORS); }
SpriteData spritePlayerPaper()     { return MK(SELECTINGPLAYPAPER); }
SpriteData spritePlayerRock()      { return MK(SELECTINGPLAYROCK); }
SpriteData spritePlayerScissors()  { return MK(SELECTINGPLAYSCISSORS); }
SpriteData spritePreparingToPlay() { return MK(PREPARINGTOPLAY); }

// Comidas (eatingX e selectingX só fase 1)
SpriteData spriteEating(uint8_t idx) {
    switch (idx) {
        case 0: return MK(EATINGSANDWICH);
        case 1: return MK(EATINGNOODLES);
        case 2: return MK(EATINGICECREAM);
        case 3: return MK(EATINGCARROT);
        case 4: return MK(EATINGAPPLE);
        case 5: return MK(EATINGDRUMSTICK);
    }
    return MK(EATINGAPPLE);
}
SpriteData spriteSelectingFood(uint8_t idx) {
    switch (idx) {
        case 0: return MK(SELECTINGSANDWICH);
        case 1: return MK(SELECTINGNOODLES);
        case 2: return MK(SELECTINGICECREAM);
        case 3: return MK(SELECTINGCARROT);
        case 4: return MK(SELECTINGAPPLE);
        case 5: return MK(SELECTINGDRUMSTICK);
    }
    return MK(SELECTINGAPPLE);
}
